package com.myname.legacyloader.bridge.fml;

import java.util.ArrayList;
import java.util.List;

/**
 * 1.7.10縺ｮ cpw.mods.fml.common.ModMetadata 莠呈鋤繧ｯ繝ｩ繧ｹ
 */
public class LegacyModMetadata {

    // MOD縺ｮ蝓ｺ譛ｬ諠・ｱ
    public String modId = "";
    public String name = "";
    public String description = "";
    public String version = "";
    public String url = "";
    public String updateUrl = "";
    public String credits = "";
    public String logoFile = "";
    public String parent = "";

    // 菴懆・ュ蝣ｱ
    public List<String> authorList = new ArrayList<>();
    public List<String> authors = new ArrayList<>();

    // 萓晏ｭ倬未菫・
    public List<String> requiredMods = new ArrayList<>();
    public List<String> dependencies = new ArrayList<>();
    public List<String> dependants = new ArrayList<>();

    // 繧ｹ繧ｯ繝ｪ繝ｼ繝ｳ繧ｷ繝ｧ繝・ヨ
    public String[] screenshots = new String[0];

    // 縺昴・莉・
    public boolean useDependencyInformation = false;
    public boolean autogenerated = true;

    public LegacyModMetadata() {
    }

    // === Getter/Setter ===

    public String getModId() {
        return modId;
    }

    public void setModId(String modId) {
        this.modId = modId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getCredits() {
        return credits;
    }

    public void setCredits(String credits) {
        this.credits = credits;
    }

    public String getLogoFile() {
        return logoFile;
    }

    public void setLogoFile(String logoFile) {
        this.logoFile = logoFile;
    }

    public List<String> getAuthorList() {
        return authorList;
    }

    public void setAuthorList(List<String> authorList) {
        this.authorList = authorList;
        this.authors = authorList;
    }

    public String getParent() {
        return parent;
    }

    public void setParent(String parent) {
        this.parent = parent;
    }

    public String[] getScreenshots() {
        return screenshots;
    }

    public void setScreenshots(String[] screenshots) {
        this.screenshots = screenshots;
    }

    // === 1.7.10繝輔ぅ繝ｼ繝ｫ繝臥峩謗･繧｢繧ｯ繧ｻ繧ｹ逕ｨ ===

    /**
     * 菴懆・Μ繧ｹ繝医ｒ譁・ｭ怜・縺ｨ縺励※蜿門ｾ・
     */
    public String getAuthorsString() {
        if (authorList != null && !authorList.isEmpty()) {
            return String.join(", ", authorList);
        }
        return "";
    }

    /**
     * 繝ｭ繧ｰ蜃ｺ蜉帷畑
     */
    @Override
    public String toString() {
        return "LegacyModMetadata{" +
                "modId='" + modId + '\'' +
                ", name='" + name + '\'' +
                ", version='" + version + '\'' +
                '}';
    }
}